# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a588d403ee800ad88104c54e56eb5ef8ed43fe1b475f7b0feaeac313afacc70219eba3049e45bb01eb778739fa122bcdb0920b4b3342a64ea1cd36af51bdf757

test:
  secret_key_base: 9e8476155f2c7aaffc6a05dc4523db9b74b53a738161fbe7bce9d895c762451a978f36e5d8db92dea25a96845029d76eb3f406eada0416cdc863bfcc977ae79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
